config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'admin/category'

  get 'admin/product'

  get 'admin/order'

  get 'admin/client'

  get 'admin/sklep'

  get 'bill/show'

  get 'bill/platnosc'

  get 'home/index'

  get 'home/contact'

  get 'home/about'

  get 'home/help'

  get 'category/show'

  root to: "home#index"

  resources :category #-> category/:id

  mount Shoppe::Engine => "/shoppe"
  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"
  post "product/:permalink", to: "products#buy"
  #root to: "products#index"
  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  Bill has_one Order
end

app/models/sklep_dane.rb
class SklepDane < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    

  def index
    @cat = Shoppe::ProductCategory.all
    @order = Shoppe::Order.all
    @product = Shoppe::Product.all
    @client = Shoppe::Customer.all
  end

  def category
  end

  def product
  end

  def order
  end

  def client
  end

  def sklep
    @sklep = SklepDane.find_by_id(1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :sklep_nazwa, :kategorie, :dane_sklep
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #wyszukuje nazwe sklepu z ustawień
  def sklep_nazwa
    @nazwa = Shoppe::Setting.find_by_id(1).value
  end
  #
  def kategorie
    @kategorie = Shoppe::ProductCategory.all
    @kategorie.group_by(&:name)
  end

  def kategoria
    @kategoria = Shoppe::ProductCategory.root.find_by_permalink(params[:permalink])
  end

  def dane_sklep
    @sklep = SklepDane.find_by_id(1)
  end

  private

  # funkcja obsługująca koszyk zamówień z biblioteki shoppe
  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end
  #funkcja sprawdzająca czy zostało dokonane zamówienie z biblioteki shoppe
  def has_order?
    !!(
      session[:order_id] &&
      @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
    )
  end

  helper_method :current_order, :has_order?

end

app/controllers/bill_controller.rb
class BillController < ApplicationController
  def show
  end

  def platnosc
    
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController


    def show
      @cat = Shoppe::ProductCategory.find_by_id(params[:format])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end

  def help
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def destroy
    current_order.destroy
    session[:order_id] = nil
    redirect_to root_path, :notice => "Koszyk jest pusty"
  end

  def checkout
    @order = Shoppe::Order.find(current_order.id)

    if request.patch?
      if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
        redirect_to checkout_payment_path
      end
    end
  end

  def payment
    @order = Shoppe::Order.find(current_order.id)

    if request.post?
      redirect_to checkout_confirmation_path
    end
  end

  def confirmation
    if request.post?
      current_order.confirm!
      session[:order_id] = nil
      redirect_to root_path, :notice => "Hurra zamówienie zostało zapisane"
    end
  end

  def bill
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # opisuje jakie dane z bazy mają być dostępne dla index
  def index
    @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    @products = @products.group_by(&:product_category)
  end

  # przydziela dane produktu do akcji show
  def show
    @product = Shoppe::Product.root.find_by_permalink(params[:permalink])
  end

  # obsługa kupowania
  def buy
    @product = Shoppe::Product.root.find_by_permalink!(params[:permalink])
    current_order.order_items.add_item(@product, 1)
    redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bill_helper.rb
module BillHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/category.html.erb
<h1>Admin#category</h1>
<p>Find me in app/views/admin/category.html.erb</p>

app/views/admin/client.html.erb
<h1>Admin#client</h1>
<p>Find me in app/views/admin/client.html.erb</p>

app/views/admin/index.html.erb
<ul>
  <li><%= link_to "Kategorie", admin_category_path %></li>
  <li><%= link_to "Produkty", admin_product_path %> </li>
</ul>

app/views/admin/order.html.erb
<h1>Admin#order</h1>
<p>Find me in app/views/admin/order.html.erb</p>

app/views/admin/product.html.erb
<h1>Admin#product</h1>
<p>Find me in app/views/admin/product.html.erb</p>

app/views/admin/sklep.html.erb
<h1>Witam tu możesz podać podstwawowe dane twojego sklepu. </h1>

  <h2>obecne dane</h2>

  <table>
      <tr>
        <th>
          Nazwa sklepu
        </th>
        <th>
          Adres
        </th>
        <th>
          NR. Konta
        </th>
      </tr>
      <tr>
        <td>
          <%= @sklep.nazwa %>
        </td>
        <td>
          <%= @sklep.adres %>
        </td>
        <td>
          <%= @sklep.konto %>
        </td>
      </tr>
  </table>

  <%= form_for @sklep do |f| %>
    <%= f.label :nazwa %>:
    <%= f.text_field :nazwa %><br />

    <%= f.label :adres %>:
    <%= f.text_field :adres %><br />

    <%= f.label :konto %>:
    <%= f.text_field :konto %><br />

    <%= f.submit %>
  <% end %>

app/views/bill/platnosc.html.erb
<div class="col-sm-4">
  <h3> Przelew </h3>
  <p> Wysyłka po otrzymaniu przelewu </p>
</div>
<div class="col-sm-4">
  <h3>Paczka pobraniowa </h3>
  <p> Wysyłka na koszt kupującego </p>
</div>
<div class="col-sm-4">
  <h3>Odbiór osobisty</h3>
  <p> obdiór towaru w sklepie </p>
</div>

app/views/category/show.html.erb
<div class="col-sm-2"><h1><%= @cat.name %></h1></div>
<div class="col-sm-8">



    <div class="lista_produktów">

      <table>
        <tbody>

        <% @cat.products.order(@sort).each do |product| %>
            <tr class="wiersz">
                <th><%= link_to product.name, product_path(product.permalink) %></th>
                <th><%= product.short_description %></th>
                <th><b>Cena:</b> <%= number_to_currency product.price %></th>
                <th><% @id=product.id %><%= image_tag product.default_image.path %> </th>
            </tr>
        <% end %>
      </tbody>
  </table>

  </div>

</div>
<div class="col-sm-2"></div>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/help.html.erb
<h1>Home#help</h1>
<p>Find me in app/views/home/help.html.erb</p>

app/views/home/index.html.erb
<%= render partial: "share/karuzela" %>

<div class="col-sm-4">

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit enim. In eget tellus risus. Praesent sed dolor urna.
Aenean iaculis sodales dui, et pharetra enim placerat vel. In sagittis viverra leo in fringilla. Donec varius leo mi,
 non lacinia nisl rutrum quis. Etiam maximus finibus nulla, tincidunt commodo mi volutpat ut. Morbi vulputate,
  diam nec tincidunt tincidunt, dolor tortor suscipit urna, a interdum lorem nisi eget velit. Suspendisse a sollicitudin est.
 Aliquam volutpat diam ac diam pretium, in faucibus magna semper. Nunc bibendum interdum dui quis viverra.
 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit enim. In eget tellus risus. Praesent sed dolor urna.
 Aenean iaculis sodales dui, et pharetra enim placerat vel. In sagittis viverra leo in fringilla. Donec varius leo mi,
  non lacinia nisl rutrum quis. Etiam maximus finibus nulla, tincidunt commodo mi volutpat ut. Morbi vulputate,
   diam nec tincidunt tincidunt, dolor tortor suscipit urna, a interdum lorem nisi eget velit. Suspendisse a sollicitudin est.
  Aliquam volutpat diam ac diam pretium, in faucibus magna semper. Nunc bibendum interdum dui quis viverra. </div>
<div class="col-sm-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit enim. In eget tellus risus. Praesent sed dolor urna.
Aenean iaculis sodales dui, et pharetra enim placerat vel. In sagittis viverra leo in fringilla. Donec varius leo mi,
 non lacinia nisl rutrum quis. Etiam maximus finibus nulla, tincidunt commodo mi volutpat ut. Morbi vulputate,
  diam nec tincidunt tincidunt, dolor tortor suscipit urna, a interdum lorem nisi eget velit. Suspendisse a sollicitudin est.
 Aliquam volutpat diam ac diam pretium, in faucibus magna semper. Nunc bibendum interdum dui quis viverra.
 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit enim. In eget tellus risus. Praesent sed dolor urna.
 Aenean iaculis sodales dui, et pharetra enim placerat vel. In sagittis viverra leo in fringilla. Donec varius leo mi,
  non lacinia nisl rutrum quis. Etiam maximus finibus nulla, tincidunt commodo mi volutpat ut. Morbi vulputate,
   diam nec tincidunt tincidunt, dolor tortor suscipit urna, a interdum lorem nisi eget velit. Suspendisse a sollicitudin est.
  Aliquam volutpat diam ac diam pretium, in faucibus magna semper. Nunc bibendum interdum dui quis viverra.</div>
<div class="col-sm-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit enim. In eget tellus risus. Praesent sed dolor urna.
Aenean iaculis sodales dui, et pharetra enim placerat vel. In sagittis viverra leo in fringilla. Donec varius leo mi,
 non lacinia nisl rutrum quis. Etiam maximus finibus nulla, tincidunt commodo mi volutpat ut. Morbi vulputate,
  diam nec tincidunt tincidunt, dolor tortor suscipit urna, a interdum lorem nisi eget velit. Suspendisse a sollicitudin est.
 Aliquam volutpat diam ac diam pretium, in faucibus magna semper. Nunc bibendum interdum dui quis viverra.
 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed elit enim. In eget tellus risus. Praesent sed dolor urna.
 Aenean iaculis sodales dui, et pharetra enim placerat vel. In sagittis viverra leo in fringilla. Donec varius leo mi,
  non lacinia nisl rutrum quis. Etiam maximus finibus nulla, tincidunt commodo mi volutpat ut. Morbi vulputate,
   diam nec tincidunt tincidunt, dolor tortor suscipit urna, a interdum lorem nisi eget velit. Suspendisse a sollicitudin est.
  Aliquam volutpat diam ac diam pretium, in faucibus magna semper. Nunc bibendum interdum dui quis viverra.</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sklep</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_order %>
    <p style="border:1px solid black;padding:10px;">
      POsiadasz <%= pluralize current_order.total_items, 'item'%> w swoim koszyku ołącznej cenie
      <%= number_to_currency current_order.total_before_tax %>.
    </p>
  <% end %>

  <%= link_to "View basket", basket_path %>
  <%= link_to "Checkout", checkout_path %>
  <%= flash[:notice] %>
  <div class="cointainet_lewa ">
    <%= render partial: "share/menu" %>
    <%= render partial: "share/head" %>
  </div>
  <div class="container">

      <div class="row">
          <div class="col-sm-12"> </div>
          <div class="col-sm-12"><%= yield %></div>
          <div class="col-sm-12"></div>
      </div>
</div>
</body>
</html>

app/views/orders/_items.html.erb
<table width='100%' border='1'>
  <thead>
    <tr>
      <td>Quantity</td>
      <td>Product</td>
      <td>Sub-Total</td>
      <td>Tax</td>
      <td>Total</td>
    </tr>
  </thead>
  <tbody>
    <% order.order_items.each do |item| %>
    <tr>
      <td><%= item.quantity %></td>
      <td><%= item.ordered_item.full_name %></td>
      <td><%= number_to_currency item.sub_total %></td>
      <td><%= number_to_currency item.tax_amount %></td>
      <td><%= number_to_currency item.total %></td>
    </tr>
    <% end %>

    <% if order.delivery_service %>
    <tr>
      <td></td>
      <td><%= order.delivery_service.name %></td>
      <td><%= number_to_currency order.delivery_price %></td>
      <td><%= number_to_currency order.delivery_tax_amount %></td>
      <td><%= number_to_currency order.delivery_price + order.delivery_tax_amount %></td>
    </tr>
    <% end %>

  </tbody>
  <tfoot>
    <tr>
      <td colspan='4'>Sub-Total</td>
      <td><%= number_to_currency order.total_before_tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Tax</td>
      <td><%= number_to_currency order.tax %></td>
    </tr>
    <tr>
      <td colspan='4'>Total</td>
      <td><%= number_to_currency order.total %></td>
    </tr>
  </tfoot>
</table>

app/views/orders/bill.html.erb
<div class="container">
  <p class="nazwa">dqwd</p>
  <p class="nazwa_2">qwd</p>
  <p class="konto">qwdqwd</p>
  wqdqwd
</div>

app/views/orders/checkout.html.erb
<h2>Checkout</h2>
<%= render 'items', :order => @order %>

<%= form_for @order, :url => checkout_path do |f| %>
  <dl>
    <dt><%= f.label :first_name, 'Name' %></dt>
    <dd><%= f.text_field :first_name %> <%= f.text_field :last_name %></dd>

    <dt><%= f.label :billing_address1, 'Address' %></dt>
    <dd><%= f.text_field :billing_address1 %></dd>
    <dd><%= f.text_field :billing_address2 %></dd>
    <dd><%= f.text_field :billing_address3 %></dd>
    <dd><%= f.text_field :billing_address4 %></dd>
    <dt><%= f.label :billing_postcode, 'Post code' %></dt>
    <dd><%= f.text_field :billing_postcode %></dd>
    <dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true %></dd>

    <dt><%= f.label :email_address %></dt>
    <dd><%= f.text_field :email_address %></dd>

    <dt><%= f.label :phone_number %></dt>
    <dd><%= f.text_field :phone_number %></dd>

    <dd><%= f.submit 'Continue' %></dd>
  </dl>
<% end %>

app/views/orders/confirmation.html.erb
<h2>Place your order</h2>
<%= render 'items', :order => current_order %>
<%= button_to "Place order" %>

app/views/orders/payment.html.erb
<h2>Make your payment</h2>
<%= form_tag do %>
  <dl>
    <dt><%= label_tag 'card_number' %></dt>
    <dd><%= text_field_tag 'card_number' %></dd>
    <dt><%= label_tag 'expiry' %></dt>
    <dd><%= text_field_tag 'expiry' %></dd>
    <dt><%= label_tag 'security_code' %></dt>
    <dd><%= text_field_tag 'security_code' %></dd>
    <dd><%= submit_tag "Continue" %></dd>
  </dl>
<% end %>

<button onclick="PrintElem()">Drukuj</button>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
</style>
<table class="tg" id="printTable">
  <tr>
    <th class="tg-031e" colspan="3"><p><sub> nazwa odbiorcy </sub></p><%= @sklep.nazwa %> <%= @sklep.adres %></th>
  </tr>
  <tr>
    <td class="tg-031e" colspan="3"><%=  @sklep.konto %></td>
  </tr>
  <tr>
    <td class="tg-031e"></td>
    <td class="tg-031e pln">PLN</td>
    <td class="tg-031e"><%= number_to_currency @order.total %></td>
  </tr>
  <tr>
    <td class="tg-031e" colspan="3">kasa słownie<br></td>
  </tr>
  <tr>
    <td class="tg-031e" colspan="3"><%= @order.first_name %><br> <%= @order.last_name %></td>
  </tr>
  <tr>
    <td class="tg-031e" colspan="3">tytuł</td>
  </tr>
  <tr>
    <td class="tg-031e">podpis<br></td>
    <td class="tg-031e">oplata</td>
    <td class="tg-031e">pieczątka</td>
  </tr>
</table>


<script type="text/javascript">
function PrintElem(elem)
    {
        $elem = document.getElementById("printTable");
        Popup($(elem).html());
    }

    function Popup(data)
    {
        var mywindow = window.open('', 'my div', 'height=400,width=600');
        mywindow.document.write('<html><head><title></title>');
        /*optional stylesheet*/ //mywindow.document.write('<link rel="stylesheet" href="main.css" type="text/css" />');
        mywindow.document.write('</head><body style="direction:rtl;"><pre>');
        mywindow.document.write(data);
        mywindow.document.write('</pre></body></html>');
        mywindow.document.close();
        mywindow.print();
        return true;
    }
</script>

app/views/orders/show.html.erb
<h2>Your basket</h2>
<%= render 'items', :order => current_order %>
<p><%= link_to 'Empty basket', basket_path, :method => :delete %></p>

app/views/products/index.html.erb
<h2>Products</h2>

<% @products.each do |category, products| %>
  <h3><%= category.name %></h3>
  <ul>
    <% products.each do |product| %>
    <li>
      <h4><%= link_to product.name, product_path(product.permalink) %></h4>
      <p><%= product.short_description %></p>
      <p><b>Cena:</b> <%= number_to_currency product.price %></p>
    </li>
    <% end %>
  </ul>
<% end %>

app/views/products/show.html.erb
<div class="col-sm-3"></div>
<div class="col-sm-6">


  <h2><%= @product.name %></h2>

  <% if @product.default_image %>
    <%= image_tag @product.default_image.path, :width => '200px', :style => "float:right" %>
  <% end %>

  <p><%= @product.short_description %></p>
  <p>
    <b><%= number_to_currency @product.price %></b>
    <%= link_to "Add to basket", product_path(@product.permalink), :method => :post %>
  </p>

  <hr>
  <%= simple_format @product.description %>
  <hr>

  <p><%= link_to "Back to list", root_path %></p>

</div>
<div class="col-sm-3"></div>

app/views/share/_head.html.erb
<div class="góra">
    <div class="row head">
        <div class="nazwa col-sm-12">
          <h3> <%= link_to @nazwa,home_index_path %> </h3>
        </div>
        <div class="menu col-sm-12">
          <%= link_to image_tag("koszyk.png", border: 0), basket_path %>
          <%= link_to image_tag("placnosc.png", border: 0), checkout_path %>
        </div>
    </div>
</div>

app/views/share/_karuzela.html.erb
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <h1> Plecaki</h1>
      </div>

      <div class="item">
          <h1> Najtaniej</h1>
      </div>

      <div class="item">
          <h1> Walaszkowski</h1>
      </div>

      <div class="item">
          <h1> Dawid</h1>
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="lewo_karuzela" aria-hidden="false"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="prawo_karuzela" aria-hidden="false"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

app/views/share/_menu.html.erb
<nav class="navbar navbar-default ">
  <div class="container-fluid">
    <div class="navbar-header">
      <ul class="nav navbar-nav">
        <% @kategorie.each do |kategoria| %>
          <li>
            <%= link_to kategoria.name, category_show_path(kategoria.id) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

</nav>
<!-- ma tu być lista dl aby było można łatwo nawigować podkategoriami -->